# Generated by Django 4.2.7 on 2025-09-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_and_more'),
        ('users', '0006_remove_insurance_veterinarian_fields'),
    ]

    operations = [
    ]
