# Generated by Django 4.2.7 on 2025-09-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20250920_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unit_number',
        ),
        migrations.AddField(
            model_name='user',
            name='block',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='house_front_view',
            field=models.ImageField(blank=True, null=True, upload_to='house_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='lot',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
